disabled_rules:
  - type_name
  - line_length
  - identifier_name
  - function_body_length
  - force_cast
  - closure_parameter_position
  - type_body_length
  - cyclomatic_complexity
  - file_length
  - function_parameter_count
  - inclusive_language

included:
  - packages/react-native-device-activity/ios/Tests
  - packages/react-native-device-activity/ios/Shared.swift
  - packages/react-native-device-activity/ios/TestHarness/reactnativedeviceactivityexample
  - packages/react-native-device-activity/targets

excluded:
  - packages/react-native-device-activity/ios/TestHarness/Pods
  - packages/react-native-device-activity/ios/TestHarness/build
