name: PR Preview

on:
  pull_request:

jobs:
  preview:
    name: Preview (pkg-pr-new)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - uses: actions/setup-node@v4
        with:
          cache: bun
          registry-url: https://registry.npmjs.org/
          scope: '@kingstinct'

      - run: bun install
      
      - run: npx pkg-pr-new publish