name: PR Preview

on:
  pull_request:

jobs:
  preview:
    name: Preview (pkg-pr-new)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - run: bun run prepublishOnly
        working-directory: packages/react-native-device-activity
      
      - run: bunx pkg-pr-new@latest publish './packages/*'