name: PR Preview

on:
  pull_request:

jobs:
  preview:
    name: Preview (pkg-pr-new)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Build package
        run: |
          cd packages/react-native-device-activity
          bun run build
          bun run prepublishOnly
      
      - name: Publish preview
        run: bunx pkg-pr-new@latest publish './packages/*'